services:
    # default configuration for services in *this* file
    _instanceof:
        ChamberOrchestra\CmsBundle\Controller\CrudControllerInterface:
            tags: [ 'cms.crud_controller' ]
            lazy: true

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    ChamberOrchestra\CmsBundle\:
        resource: '../../'
        exclude: "../../{DependencyInjection,Resources,Exception,Maker,Controller,Events,Form/Dto,Form/Normalizer,Form/Transformer,Regex,Processor/Reflection,Configurator,EntityRepository,tests}"

    #    ChamberOrchestra\CmsBundle\Processor\Instantiator:
    #        arguments:
    #            $cacheItemPool:

    ChamberOrchestra\CmsBundle\EventSubscriber\SetVersionSubscriber:
        class: ChamberOrchestra\CmsBundle\EventSubscriber\SetVersionSubscriber
        autoconfigure: true
        autowire: false
        arguments:
            - 'build_id'
